### ISSUE TITLE
Uncaught TypeError: Cannot read property 'includeInto' of undefined

### ISSUE THREAD

**Issue by syrsly** [abe33/atom-tablr#101]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package 1.8.3

### Stack Trace

Uncaught TypeError: Cannot read property 'includeInto' of undefined

```
At C:\Users\User\.atom\packages\tablr\lib\mixins\pool.js:65

TypeError: Cannot read property 'includeInto' of undefined
    at Function.pool (/packages/tablr/lib/mixins/pool.js:65:11)
    at Function.initClass (/packages/tablr/lib/table-element.js:75:10)
    at /packages/tablr/lib/table-element.js:2134:31)
    at /packages/tablr/lib/table-element.js:2136:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.28.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.28.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.28.0/resources/app/src/native-compile-cache.js:66:33)
    at Object.tablrViewProvider (/packages/tablr/lib/tablr.js:152:43)
    at Object.viewRegistry.addViewProvider.model [as createView] (~/AppData/Local/atom/app-1.28.0/resources/app/src/package.js:538:51)
    at ViewRegistry.createView (~/AppData/Local/atom/app-1.28.0/resources/app/src/view-registry.js:154:34)
    at ViewRegistry.getView (~/AppData/Local/atom/app-1.28.0/resources/app/src/view-registry.js:127:25)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:138:33)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.28.0/resources/app/src/pane.js:443:26)
    at Pane.activateItem (~/AppData/Local/atom/app-1.28.0/resources/app/src/pane.js:583:18)
    at TablrJson.open (/packages/tablr-json/lib/tablr-json.js:83:10)
    at HTMLElement.tablrJsonOpen (/packages/tablr-json/lib/tablr-json.js:17:37)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.28.0/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.28.0/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.28.0/resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.28.0/resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -2:33.3.0 core:select-all (input.hidden-input)
     -2:32.5.0 core:paste (input.hidden-input)
     -2:30.3.0 core:save (input.hidden-input)
     -1:56.5.0 core:confirm (input.hidden-input)
     -0:20.9.0 tablr-json:open (input.hidden-input)
```

### Non-Core Packages

```
atom-json-editor 0.4.1 
atom-wrap-in-tag 0.6.0 
auto-update-plus 0.5.8 
browse 1.10.8 
build 0.70.0 
busy-signal 1.4.3 
color-picker 2.3.0 
ctrl-dir-scroll 0.2.5 
find-and-replace-with-prev 0.210.0 
intentions 1.1.5 
linter 2.2.0 
linter-json-lint 0.1.3 
linter-ui-default 1.7.1 
minimap 4.29.8 
multi-cursor 2.1.5 
satisfy-dependencies 0.4.2 
scroll-searcher 5.2.0 
set-syntax 0.4.0 
split-diff 1.5.2 
sublime 0.5.0 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.4 
sublime-word-navigation 0.2.0 
sublimify 0.10.0 
tablr 1.8.3 
tablr-json 0.1.0 
tag 0.5.0 
text-manipulation 0.6.0 
```

**Comment by pjnr1** [comment]
Duplicate of #100

**Comment by gruntaway** [comment]
Having the same issue.

**Comment by amitbattase** [comment]
Having the same issue.
