### ISSUE TITLE
Uncaught ReferenceError: __CUSTOM_HTML_ELEMENTS_CLASSES__ is not defined

### ISSUE THREAD

**Issue by peter-dye** [abe33/atom-tablr#110]
[Enter steps to reproduce:]

1. Right click on .csv file in finder and select open with atom
2. Didn't change any options and clicked Open Table Editor
3. Error appeared

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.1
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package 1.8.3

### Stack Trace

Uncaught ReferenceError: __CUSTOM_HTML_ELEMENTS_CLASSES__ is not defined

```
At /Users/peterdye/.atom/packages/tablr/node_modules/atom-utils/lib/register-or-update-element.js:55

ReferenceError: __CUSTOM_HTML_ELEMENTS_CLASSES__ is not defined
    at module.exports (/packages/tablr/node_modules/atom-utils/lib/register-or-update-element.js:55:5)
    at element (/packages/tablr/lib/decorators/element.js:6:10)
    at Function.initClass (/packages/tablr/lib/csv-progress-element.js:11:12)
    at /packages/tablr/lib/csv-progress-element.js:59:37)
    at /packages/tablr/lib/csv-progress-element.js:61:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at HTMLElement.displayProgress (/packages/tablr/lib/csv-editor-element.js:198:28)
    at HTMLElement.ensureProgress (/packages/tablr/lib/csv-editor-element.js:193:39)
    at /packages/tablr/lib/csv-editor-element.js:61:12
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190051)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1191492)
    at CSVEditor.openTableEditor (/packages/tablr/lib/csv-editor.js:270:18)
    at /packages/tablr/lib/csv-editor-element.js:154:20)
    at HTMLButtonElement.listener (/packages/tablr/node_modules/atom-utils/lib/mixins/events-delegation.js:108:41)
```

### Commands

```
```

### Non-Core Packages

```
arduino-upload 1.8.0 
atom-clock 0.1.18 
atom-ide-debugger-python 0.7.3 
atom-ide-outline 1.16.0 
atom-ide-ui 0.13.0 
file-icons 2.1.46 
ide-python 1.7.2 
ide-rust 0.22.0-beta.3 
kite 0.197.0 
language-arduino 0.4.3 
language-cython 0.3.0 
language-matlab 0.2.1 
minimap 4.38.2 
pdf-view 0.72.0 
platformio-ide-terminal 2.10.1 
python-debugger 0.2.0 
python-tools 0.6.9 
tablr 1.8.3 
```

**Comment by squeezer44** [comment]
Same for me with this stack tracke:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: SQUEEZER44
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package 1.8.3


### Stack Trace

Uncaught ReferenceError: __CUSTOM_HTML_ELEMENTS_CLASSES__ is not defined

```
At C:\Users\NAME\.atom\packages\tablr\node_modules\atom-utils\lib\register-or-update-element.js:55

ReferenceError: __CUSTOM_HTML_ELEMENTS_CLASSES__ is not defined
    at module.exports (/packages/tablr/node_modules/atom-utils/lib/register-or-update-element.js:55:5)
    at element (/packages/tablr/lib/decorators/element.js:6:10)
    at Function.initClass (/packages/tablr/lib/csv-progress-element.js:11:12)
    at /packages/tablr/lib/csv-progress-element.js:59:37)
    at /packages/tablr/lib/csv-progress-element.js:61:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at HTMLElement.displayProgress (/packages/tablr/lib/csv-editor-element.js:198:28)
    at HTMLElement.ensureProgress (/packages/tablr/lib/csv-editor-element.js:193:39)
    at /packages/tablr/lib/csv-editor-element.js:61:12
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:1190511)
    at Emitter.emit (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:1191952)
    at CSVEditor.openTableEditor (/packages/tablr/lib/csv-editor.js:270:18)
    at /packages/tablr/lib/csv-editor-element.js:154:20)
    at HTMLButtonElement.listener (/packages/tablr/node_modules/atom-utils/lib/mixins/events-delegation.js:108:41)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-csv-markdown 1.0.4 
atom-language-r 1.4.8 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-python-run 0.9.7 
atom-terminal-panel 4.4.4 
autocomplete-python 1.17.0 
autocomplete-xml 0.11.0 
bottom-dock 0.4.4 
build 0.70.0 
busy-signal 2.0.1 
click-link 1.0.11 
color-picker 2.3.0 
copy-find-results 0.2.0 
docblockr 0.13.7 
file-icons 2.1.47 
git-diff-details 1.4.0 
git-log 0.4.1 
git-plus 8.7.1 
git-plus-toolbar 1.0.1 
git-time-machine 2.1.0 
gitkraken-glo 1.0.2 
highlight-column 0.5.4 
highlight-line 0.12.0 
highlight-selected 0.17.0 
hyperclick 0.1.5 
intentions 1.1.5 
kite 0.204.0 
language-csv 1.1.2 
language-docker 1.1.8 
language-ini 1.23.0 
language-markdown 0.37.0 
linter 3.3.1 
linter-pycodestyle 2.1.3 
linter-tidy 2.4.0 
linter-ui-default 3.3.1 
markdown-img-paste 0.4.0 
markdown-pdf 2.3.3 
markdown-scroll-sync 2.1.2 
markdown-writer 2.11.11 
minimap 4.39.12 
minimap-find-and-replace 5.0.8 
minimap-highlight-selected 4.6.5 
open-in-browser 0.5.2 
pandoc-convert 1.1.1 
pdfjs-viewer 1.0.0 
platformio-ide-debugger 1.2.6 
pretty-json 2.1.2 
print-code 0.7.1 
project-manager 3.3.8 
python-indent 1.2.6 
python-tools 0.6.9 
split-diff 1.6.1 
sync-settings 5.2.9 
tablr 1.8.3 
teletype 0.13.4 
todo-show 2.3.2 
tool-bar 1.4.2 
tool-bar-markdown-writer 0.5.1 
xml-formatter 0.13.0 
```
