### ISSUE TITLE
Uncaught TypeError: Cannot set property 'value' of undefined

### ISSUE THREAD

**Issue by thebekhruz** [abe33/atom-tablr#115]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.63.0 x64
**Electron**: 11.5.0
**OS**: macOS 13.0.1
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package 1.8.3

### Stack Trace

Uncaught TypeError: Cannot set property 'value' of undefined

```
At /Users/thebekhruz/.atom/packages/tablr/lib/csv-editor-form-element.js:324

TypeError: Cannot set property 'value' of undefined
    at HTMLElement.initializeDefaults (/packages/tablr/lib/csv-editor-form-element.js:324:33)
    at /packages/tablr/lib/csv-editor-form-element.js:393:38
```

### Commands

```
```

### Non-Core Packages

```
atom-file-icons 0.7.1 
atom-java-snippets 0.5.1 
atom-material-syntax 1.0.8 
atom-sublime-monokai-syntax 0.4.4 
autocomplete-java 1.2.7 
base16-ocean-dark-syntax-theme 0.1.10 
black-ui 0.3.7 
blueforest-syntax 0.5.1 
busy-signal 2.0.1 
ephyx-syntax 0.6.0 
fold-comments 0.6.0 
google-java-format 0.0.4 
Hyrule-atom 1.2.1 
intentions 2.1.1 
linter 3.4.0 
linter-ui-default 3.4.1 
operator-mono 0.11.0 
platformio-ide-terminal 2.10.1 
seti-syntax 1.2.0 
seti-ui 1.11.0 
tablr 1.8.3 
todo-manager 0.2.10 
```

**Comment by orkenstein** [comment]
Getting the same
