### ISSUE TITLE
Uncaught TypeError: atom.project.open is not a function

### ISSUE THREAD

**Issue by christiaan-lombard** [abe33/atom-tablr#15]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0-beta2
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package, v0.6.1

### Stack Trace

Uncaught TypeError: atom.project.open is not a function

```
At /C:/Users/christiaan/.atom/packages/tablr/lib/csv-editor.coffee:221

TypeError: atom.project.open is not a function
    at CSVEditor.module.exports.CSVEditor.openTextEditor (file:///C:/Users/christiaan/.atom/packages/tablr/lib/csv-editor.coffee:154:18)
    at Object.formSubscriptions.add.subscribeTo.click [as __NONE__] (file:///C:/Users/christiaan/.atom/packages/tablr/lib/csv-editor-element.coffee:76:16)
    at HTMLButtonElement.listener (C:\Users\christiaan\.atom\packages\tablr\node_modules\atom-utils\lib\mixins\events-delegation.js:108:41)
```

### Commands

```
     -9:56.2.0 core:copy (atom-text-editor.editor.is-focused)
     -9:53.7.0 core:paste (atom-text-editor.editor.is-focused)
  2x -9:53.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "monokai"
    ],
    "projectHome": "D:\\dev",
    "disabledPackages": [
      "grunt-runner",
      "jshint"
    ],
    "excludeVcsIgnoredPaths": false,
    "autoHideMenuBar": true
  },
  "tablr": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
atom-beautify, v0.28.17
atom-material-ui, v0.8.0
build, v0.48.0
docblockr, v0.7.3
emmet, v2.3.14
file-icons, v1.6.11
language-blade, v0.16.0
language-dotenv, v1.0.0
language-nginx, v0.6.1
line-ending-converter, v1.3.2
monokai, v0.18.0
pretty-json, v0.4.1
project-manager, v2.6.5
tablr, v0.6.1
tool-bar, v0.1.9
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by christiaan-lombard** [comment]
Steps to reproduce:

  1. Open the CSV:

```csv
"ZZZZZZFTP","secret","secret","V","1","0"
"netcash_secret","2015/11/13"
"YSACC0000007","First Last","LP","1","000","000","000","000","someuser@somedomain.co.za","","","","","","0","YSDOT0000001 YSDOT0000002 YSDOT0000003 YSDOT000000","4",""
"YSACC0000008","First Last","","2","000","000","000","000","someuser@somedomain.co.za","","","","","","0","YSDOT0000005","",""
"YSACC0000009","First Last","DL","1","000","000","000","000","someuser@somedomain.com","","","","","","0","YSDOT0000006 YSDOT0000007 YSDOT0000008","",""
"YSACC0000010","First Last","","1","000","000","000","000","someuser@somedomain.co.za","","","","","","0","YSDOT0000009 YSDOT0000010 YSDOT0000011 YSDOT000001","2 YSDOT0000013 YSDOT0000014 YSDOT0000015 YSDOT0000","016 YSDOT0000017 YSDOT0000018 YSDOT0000019"
"YSACC0000012","First Last","","1","000","000","000","000","someuser@somedomain.co.za","","","","","","0","YSDOT0000020 YSDOT0000021 YSDOT0000022 YSDOT000002","3 YSDOT0000024 YSDOT0000025 YSDOT0000026",""
"YSACC0000015","First Last","","1","000","000","000","000","someuser@somedomain.co.za","","","","","","0","YSDOT0000027 YSDOT0000028","",""
"YSACC0000016","First Last","","1","000","000","000","000","someuser@somedomain.co.za","","","","","","0","YSDOT0000029","",""
"YSACC0000017","First Last","","1","000","000","000","000","someuser@somedomain.com","","","","","","0","YSDOT0000030","",""
"##END##","2391121"
```

  2. Click 'OPEN TEXT EDITOR'

**Comment by abe33** [comment]
Hi @christiaan-lombard, I had the fix prepared for some time but was not expecting v1.2.0 to be released this soon. v0.6.3 should address this issue.

**Comment by havoc74** [comment]
First, I'd like to say that I love this package and use it quite often!

I upgraded to v0.6.3 and the problem persists:

[Enter steps to reproduce below:]

1. Open any CSV
2. Click "Open Text Editor"

**Atom Version**: 1.2.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package, v0.6.3


### Stack Trace

Uncaught TypeError: atom.project.open is not a function

```
At /C:/Users/XXXXX/.atom/packages/tablr/lib/csv-editor.coffee:221

TypeError: atom.project.open is not a function
    at CSVEditor.module.exports.CSVEditor.openTextEditor (file:///C:/Users/XXXXX/.atom/packages/tablr/lib/csv-editor.coffee:154:18)
    at Object.formSubscriptions.add.subscribeTo.click [as __NONE__] (file:///C:/Users/XXXXX/.atom/packages/tablr/lib/csv-editor-element.coffee:76:16)
    at HTMLButtonElement.listener (C:\Users\XXXXX\.atom\packages\tablr\node_modules\atom-utils\lib\mixins\events-delegation.js:108:41)
```

### Commands

```
     -9:25.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -9:25.2.0 core:copy (atom-text-editor.editor.is-focused)
     -9:24.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -9:24.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -9:23.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -9:23.4.0 core:paste (atom-text-editor.editor.is-focused)
     -9:18.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:47.2.0 settings-view:uninstall-packages (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "tablr": {}
}
```

### Installed Packages

```coffee
# User
atom-grails, v0.1.0
language-groovy, v0.4.0
pretty-json, v0.4.1
split-diff, v0.4.5
svn, v0.0.8
tablr, v0.6.3

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hmm, I may have overlooked something, the tests are green and this case is covered, and I don't reproduce this on stable. Do you still get it after an update (I believe it's again an issue with custom elements that are not updated with the rest of the package)

**Comment by havoc74** [comment]
I will update and test again, maybe shutting down Atom will work as well.
I'll get back to you as soon as I have a chance to test again.

Thank You.

**Comment by havoc74** [comment]
I am very sorry, I have not had a chance to test this again and noticed that v0.7,0 was available. So I've updated and can confirm that this bug can no longer be reproduced.
Thank you @abe33 :)
