### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Ninja-1** [abe33/atom-tablr#16]
[Enter steps to reproduce below:]

1. Select field
2. Change value
3. Press enter

**Atom Version**: 1.2.1
**System**: Microsoft Windows 10 Home
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package, v0.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /C:/Users/Dalton/.atom/packages/tablr/lib/table-element.coffee:1221

TypeError: Cannot read property 'name' of undefined
    at tablr-editor.module.exports.TableElement.confirmColumnEdit (file:///C:/Users/Dalton/.atom/packages/tablr/lib/table-element.coffee:834:43)
    at atom-text-editor.textEditorSubscriptions.add.atom.commands.add.core:confirm (file:///C:/Users/Dalton/.atom/packages/tablr/lib/table-element.coffee:897:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Dalton\AppData\Local\atom\app-1.2.1\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Dalton\AppData\Local\atom\app-1.2.1\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Dalton\AppData\Local\atom\app-1.2.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Dalton\AppData\Local\atom\app-1.2.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Dalton\AppData\Local\atom\app-1.2.1\resources\app.asar\src\window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (C:\Users\Dalton\AppData\Local\atom\app-1.2.1\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -2:45.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -2:41.9.0 core:backspace (tablr-editor.)
     -2:38.5.0 core:confirm (tablr-editor.)
  5x -2:35 core:undo (tablr-editor.)
     -2:26.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:23.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:13.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:10.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -2:05.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:02.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  9x -1:58.7.0 core:undo (tablr-editor.)
  4x -1:42.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:40.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.8.0
language-jade, v0.6.2
linter, v1.11.2
linter-csslint, v1.1.0
linter-golinter, v1.0.0
linter-jade, v0.3.2
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
linter-scss-lint, v2.4.0
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.5
minimap-find-and-replace, v4.3.2
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
pigments, v0.18.1
tablr, v0.7.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @Ninja-1, thanks for the report, looks like you're right, I also get errors when editing columns' name but still don't have the reason why. I'll take a deeper look at this later on.

**Comment by lparsons** [comment]
Getting this error on latest version

**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package, v1.8.0


### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /Users/lparsons/.atom/packages/tablr/lib/table-element.js:1336

TypeError: Cannot read property 'name' of undefined
    at tablr-editor.confirmColumnEdit (/Users/lparsons/.atom/packages/tablr/lib/table-element.js:1336:49)
    at atom-text-editor.textEditorSubscriptions.add.atom.commands.add.core:confirm.e (/Users/lparsons/.atom/packages/tablr/lib/table-element.js:1406:14)
    at atom-text-editor.<anonymous> (/Users/lparsons/.atom/packages/tablr/lib/table-element.js:30:17)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  3x -2:22.6.0 core:undo (input.hidden-input)
     -1:12.9.0 tablr:insert-row-before (input.hidden-input)
     -1:00.8.0 tablr:insert-column-before (input.hidden-input)
     -0:49.5.0 core:delete (input.hidden-input)
  2x -0:40 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:39.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:39.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:17.9.0 core:move-down (input.hidden-input)
     -0:17.5.0 core:move-up (input.hidden-input)
     -0:13.1.0 tablr:delete-column (input.hidden-input)
     -0:09.5.0 tablr:insert-column-after (input.hidden-input)
     -0:03.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:03.5.0 core:copy (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "projectHome": "/Users/lparsons/Documents/projects",
    "telemetryConsent": "limited"
  },
  "tablr": {
    "supportedCsvExtensions": [
      "csv",
      "tsv",
      "CSV",
      "TSV",
      "expected"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (inactive)
autocomplete-python, v1.8.26 (active)
git-plus, v7.0.5 (active)
kite, v0.6.2 (active)
language-matlab, v0.2.1 (active)
language-r, v0.4.1 (active)
linter, v1.11.18 (active)
linter-flake8, v2.1.4 (inactive)
linter-markdown, v3.0.2 (active)
linter-mixed-indent, v1.1.0 (active)
markdown-writer, v2.6.2 (inactive)
minimap, v4.25.7 (active)
python-tools, v0.6.8 (active)
Sublime-Style-Column-Selection, v1.7.2 (active)
sync-settings, v0.8.1 (active)
tablr, v1.8.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```
