### ISSUE TITLE
Uncaught Error: Number of columns is inconsistent on line 104

### ISSUE THREAD

**Issue by sahina** [abe33/atom-tablr#48]
This is a valid CSV file, at least from what I can see opening it in numbers.

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package, v1.2.2

### Stack Trace

Uncaught Error: Number of columns is inconsistent on line 104

```
At events.js:141

Error: Number of columns is inconsistent on line 104
    at Error (native)
    at [object Object].Parser.__push (/Users/asahin/.atom/packages/tablr/node_modules/csv/node_modules/csv-parse/lib/index.js:208:26)
    at [object Object].Parser.__write (/Users/asahin/.atom/packages/tablr/node_modules/csv/node_modules/csv-parse/lib/index.js:378:14)
    at [object Object].Parser._flush (/Users/asahin/.atom/packages/tablr/node_modules/csv/node_modules/csv-parse/lib/index.js:177:10)
    at [object Object].<anonymous> (_stream_transform.js:118:12)
    at [object Object].g (events.js:260:16)
    at emitNone (events.js:67:13)
    at [object Object].emit (events.js:166:7)
    at prefinish (_stream_writable.js:458:12)
    at finishMaybe (_stream_writable.js:466:7)
    at afterWrite (_stream_writable.js:347:3)
    at doNTCallbackMany (node.js:487:18)
    at process._tickCallback (node.js:385:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v3.0.0
api-blueprint-preview, v0.7.0
atom-jinja2, v0.5.0
atom-typescript, vundefined
atom-wallaby, v1.0.7
autocomplete-go, v1.0.8
autocomplete-php, v0.3.7
autocomplete-python, v1.7.2
autocomplete-wordpress-hooks, v0.2.0
builder-go, v1.0.0
coffee-compile, v0.21.1
color-picker, v2.1.1
emmet, v2.4.3
environment, v1.2.0
go-config, v1.1.4
go-debug, v0.1.11
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
language-api-blueprint, v1.0.2
language-babel, v2.18.2
language-ejs, v0.2.0
language-elixir, v0.12.3
language-ini, v1.16.0
language-jade, v0.7.1
language-rust, v0.4.6
less-autocompile, v1.0.0
linter, v1.11.4
linter-eslint, vundefined
linter-php, v1.2.0
linter-rust, v0.4.5
merge-conflicts, v1.4.2
navigator-godef, v1.0.3
php-cs-fixer, v2.5.6
python-tools, v0.6.7
react, v0.15.0
tablr, v1.2.2
terminal-panel, v1.14.1
tester-go, v1.0.4
wordpress-api, v1.2.2

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @sahina, 

I'm not able to reproduce that even with a file with completely random row length. Could share with me a file that triggers this error?
