### ISSUE TITLE
Try to edit empty file

### ISSUE THREAD

**Issue by dapetcu21** [abe33/atom-tablr#53]
[Enter steps to reproduce below:]

1. Create empty file
2. Open with tablr
3. Try to edit something

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package, v1.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /Users/da_petcu21/.atom/packages/tablr/lib/table-element.coffee:840

TypeError: Cannot read property 'name' of undefined
    at tablr-editor.module.exports.TableElement.startCellEdit (/Users/da_petcu21/.atom/packages/tablr/lib/table-element.coffee:840:5)
    at tablr-editor.atom.commands.add.core:confirm (/Users/da_petcu21/.atom/packages/tablr/lib/table-element.coffee:1589:25)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:50.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.6.0 tree-view:toggle-focus (div.package-detail.panels-item)
     -0:20.8.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:19.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:16.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-eslint",
      "omnisharp-atom",
      "json-schema"
    ],
    "packagesWithKeymapsDisabled": [
      "devdocs",
      "activate-power-mode"
    ],
    "projectHome": "/Users/da_petcu21/Programare",
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
atom-jade, v0.3.0
atom-yeoman, v0.3.15
autocomplete-clang, v0.9.3
autocomplete-glsl, v0.2.3
autocomplete-paths, v1.0.2
devdocs, v0.2.1
file-icons, v1.7.9
language-glsl, v2.0.1
language-haskell, v1.7.15
language-lex-flex, v0.1.0
linter, v1.11.4
linter-clang, v3.4.4
linter-glsl, v2.0.2
linter-js-standard, v3.3.2
markdown-themeable-pdf, v1.0.1
merge-conflicts, v1.4.2
pigments, v0.26.2
python-indent, v0.4.3
react, v0.15.0
tablr, v1.3.1
the-closer, v0.6.0
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @dapetcu21, thanks for the report, it's probably because there's no columns nor rows yet. I should probably at least create one when an edit attempt is made.
