### ISSUE TITLE
Uncaught TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by Off76** [abe33/atom-tablr#64]
After updating to the latest version of Atom, this error is showing every time I try to access to atom preference, which is preventing me to access to preference.

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: linux 4.7.2
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package, v1.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'join' of undefined

```
At /home/off/.atom/packages/tablr/lib/tablr.coffee:22

TypeError: Cannot read property 'join' of undefined
    at /home/off/.atom/packages/tablr/lib/tablr.coffee:22:76
    at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app.asar/src/workspace.js:504:22)
    at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app.asar/src/workspace.js:439:19)
    at atom-workspace.atom.commands.add.settings-view:open (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/main.js:60:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:00.0 settings-view:open (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "packagesWithKeymapsDisabled": [
      "lines",
      "linter-js-standard-jsx"
    ],
    "themes": [
      "northem-atom-ui",
      "northem-atom-syntax"
    ]
  },
  "tablr": {
    "csvEditor": {
      "columnDelimiter": ";"
    }
  }
}
```

### Installed Packages

```coffee
# User
an-old-hope-syntax, v0.5.0 (inactive)
atom-easy-jsdoc, v4.6.0 (inactive)
atom-gooey-syntax, v0.2.1 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-ternjs, v0.15.0 (active)
autocomplete-modules, v1.6.1 (active)
chester-atom-syntax, v0.1.1 (inactive)
color-picker, v2.2.2 (active)
elasticsearch-client, v0.9.4 (inactive)
expose, v0.12.1 (inactive)
file-icons, v1.7.19 (active)
firewatch-syntax, v1.0.1 (inactive)
flatten-json, v0.1.4 (inactive)
genesis-ui, v0.5.0 (inactive)
imdone-atom, v1.3.30 (active)
language-apache, v1.5.0 (active)
language-pug, v0.0.17 (active)
language-velocity, v0.1.2 (active)
lines, v0.13.1 (inactive)
linter, v1.11.16 (active)
linter-eslint, v7.2.4 (active)
linter-json-lint, v0.1.1 (active)
markdown-preview-plus, v2.4.0 (active)
material-ui, v1.0.9 (inactive)
minimap, v4.24.7 (active)
native-ui, v0.18.3 (inactive)
northem-atom-syntax, v0.22.0 (active)
northem-atom-ui, v0.5.0 (active)
northem-light-atom-ui, v0.4.0 (inactive)
nucleus-dark-ui, v0.9.3 (inactive)
predawn-ui, v1.0.2 (inactive)
tablr, v1.5.0 (active)
tasks, v2.6.3 (active)
tomorrow-night-eighties-syntax, v0.17.0 (inactive)
yeti-ui, v0.1.6 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @Off76, there's definitely a issue in the package as it should not fail in that case. 
However it looks there's also something weird with your config. You've got this error because the `tablr.supportedCsvExtensions` setting is null, meaning that in practice, even if I guard agaisnt an error in that situation, you still won't be able to open any file with tablr since there's no extensions it'll support. I'm not sure whether I should fallback to the default in that particular case.

**Comment by Off76** [comment]
That's strange, have you an idea of how I could uninstall this package ? Since I can't access to preferences? Thanks for your answer  :+1:

**Comment by abe33** [comment]
This should not be necessary with the latest version (1.5.1), if the setting is null I fallback on the setting's default. But it'll also works with a reisintall :).
