### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clearUndoStack' of undefined

### ISSUE THREAD

**Issue by duncdrum** [abe33/atom-tablr#93]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package 1.8.3

### Stack Trace

Uncaught TypeError: Cannot read property 'clearUndoStack' of undefined

```
At /Users/HALmob/.atom/packages/tablr/lib/table-element.js:1309

TypeError: Cannot read property 'clearUndoStack' of undefined
    at HTMLElement.startCellEdit (/packages/tablr/lib/table-element.js:1309:36)
    at Object.dblclick (/packages/tablr/lib/table-element.js:341:29)
    at HTMLDivElement.listener (/packages/minimap/node_modules/atom-utils/lib/mixins/events-delegation.js:108:41)
```

### Commands

```
     -8:08.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
  2x -7:59.9.0 existdb:run (input.hidden-input)
     -6:06.3.0 open-on-github:file (ul.list-inline.tab-bar.inset-panel)
     -4:35.4.0 core:confirm (input.hidden-input)
     -3:55.6.0 core:save (input.hidden-input)
     -3:51.9.0 existdb:run (input.hidden-input)
     -3:41.2.0 existdb:upload-selected (span.name.icon.graph-icon.light-red)
     -3:31.5.0 existdb:toggle-tree-view (div.tool-panel.tree-view)
     -3:04.0 existdb:upload-selected (li.file.entry.list-item.selected)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-live-server 2.1.2 
autocomplete-xml 0.9.4 
build 0.69.0 
build-sassc 0.8.2 
busy 0.7.0 
busy-signal 1.4.3 
emmet 2.4.3 
existdb 0.6.0 
file-icons 2.1.12 
htmlhint 1.1.4 
hyperclick 0.1.5 
intentions 1.1.5 
language-jsoniq 1.8.0 
linter 2.2.0 
linter-autocomplete-jing 0.8.2 
linter-markdown 5.2.0 
linter-ui-default 1.6.10 
logo-file-icons 1.12.0 
markdown-image-helper 1.0.4 
merge-conflicts 1.4.5 
minimap 4.29.7 
open-html-in-browser 0.2.0 
pigments 0.40.2 
project-manager 3.3.5 
tablr 1.8.3 
todo-show 2.1.0 
wordcount 2.10.4 
xml-common-schemata 0.0.3 
xml-tools 0.2.1 
Zen 0.18.0 
zotero-citations 0.19.1 
```

**Comment by jeremydouglass** [comment]
Steps to reproduce for me:

1. open a CSV file with tablr by completing the setting menu
2. either:
   -  click twice in any cell to edit
   -  click once in any cell, then press any key to edit

Atom: 1.21.1 x64  
OS: Mac OS X 10.12.6

**Comment by JasonJunMa** [comment]
I got same issue here.

[Enter steps to reproduce:]

1. open a CSV file with tablr by completing the setting menu
2. click twice in any cell to edit

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package 1.8.3


### Stack Trace

Uncaught TypeError: Cannot read property 'clearUndoStack' of undefined

```
At /Users/jason/.atom/packages/tablr/lib/table-element.js:1309

TypeError: Cannot read property 'clearUndoStack' of undefined
    at HTMLElement.startCellEdit (/packages/tablr/lib/table-element.js:1309:36)
    at Object.dblclick (/packages/tablr/lib/table-element.js:341:29)
    at HTMLDivElement.listener (/packages/tablr/node_modules/atom-utils/lib/mixins/events-delegation.js:108:41)
```

### Commands

```
     -4:47.5.0 application:reopen-project (atom-pane.pane.active)
  2x -4:47.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-one-dark-ui)
     -4:14.6.0 command-palette:toggle (input.hidden-input)
     -4:11 core:confirm (input.hidden-input)
     -4:11 application:about (input.hidden-input)
     -2:05.5.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-beautify 0.30.5 
auto-encoding 0.7.0 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.11.0 
file-icons 2.1.13 
git-plus 7.10.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-lua 0.9.11 
language-pascal 0.20.2 
linter 2.2.0 
linter-clang 4.1.2 
linter-javac 1.9.4 
linter-lua 1.0.4 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-split-diff 0.3.7 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
split-diff 1.5.1 
Sublime-Style-Column-Selection 1.7.4 
tablr 1.8.3 
```


[Enter steps to reproduce:]

1. open a CSV file with tablr by completing the setting menu
2. click once in any cell, then press any key to edit

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package 1.8.3


### Stack Trace

Uncaught TypeError: Cannot read property 'clearUndoStack' of undefined

```
At /Users/jason/.atom/packages/tablr/lib/table-element.js:1309

TypeError: Cannot read property 'clearUndoStack' of undefined
    at HTMLElement.startCellEdit (/packages/tablr/lib/table-element.js:1309:36)
    at /packages/tablr/lib/table-element.js:283:16)
    at HTMLInputElement.listener (/packages/tablr/node_modules/atom-utils/lib/mixins/events-delegation.js:108:41)
```

### Commands

```
     -2:47.4.0 application:reopen-project (atom-pane.pane.active)
  2x -2:47.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-one-dark-ui)
     -2:14.6.0 command-palette:toggle (input.hidden-input)
     -2:11 core:confirm (input.hidden-input)
     -2:11 application:about (input.hidden-input)
     -0:05.5.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-beautify 0.30.5 
auto-encoding 0.7.0 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.11.0 
file-icons 2.1.13 
git-plus 7.10.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-lua 0.9.11 
language-pascal 0.20.2 
linter 2.2.0 
linter-clang 4.1.2 
linter-javac 1.9.4 
linter-lua 1.0.4 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-split-diff 0.3.7 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
split-diff 1.5.1 
Sublime-Style-Column-Selection 1.7.4 
tablr 1.8.3 
```

**Comment by lincolnep** [comment]
If you comment out theses 2 lines in table-element.js then you won't get this error showing up.

Line 1309:    this.editor.getBuffer().history.clearUndoStack()
Line 1310:    this.editor.getBuffer().history.clearRedoStack()

Comment out with // in-front of the line

Restart Atom and it should not show that error anymore.

**Comment by jeremydouglass** [comment]
@lincolnep -- so, disable the undo/redo stack calls.... submit that as a pull request?

**Comment by neelsmith** [comment]
Tried that, and atom hung up on me when editing delimited text with tablr.  Had to force quit.

**Comment by lincolnep** [comment]
@neelsmith Do you have a sample csv that hangs atom to have a look at?

I have tryed a few csv files and it looks to work great on my end.
I am on Windows 10 if it make a difference.

I have attached the csv that i am testing on could you give that a go and let me know if it crashes atom.
[SampleCSVFile_11kb.zip](https://github.com/abe33/atom-tablr/files/1459852/SampleCSVFile_11kb.zip)

**Comment by siso** [comment]
@lincolnep https://github.com/lincolnep/atom-tablr/commit/4a6b91c6cbdca167450061676ce2576f8ae6dcac fixes the issue on OS X for me

**Comment by Guipotenciano** [comment]
I don't know if this is the best way, but works for me (on MacOS).

(MacOS) Go to ATOM > Preferences
(Windows) Go to File > Settings

On Settings window click in "Open Config Folder"
Navigate to **.atom > packages > tablr > lib > table-elements.js** (open it)

**Search for**
```
this.editor.getBuffer().history.clearUndoStack()
this.editor.getBuffer().history.clearRedoStack() 
```
**Replace for**
```
if(this.editor.getBuffer().history != undefined){
    this.editor.getBuffer().history.clearUndoStack()
    this.editor.getBuffer().history.clearRedoStack() 
}
```

**Comment by AminSarafraz** [comment]
Is there any hopes on fixing this issue any time soon?

**Comment by jeremydouglass** [comment]
Well, @abe33 hasn't chimed in for two months, and hasn't committed in seven months, so... probably not anytime soon?

@lincolnep has forked and patched. You could install that manually:

https://github.com/lincolnep/atom-tablr

**Comment by vafagh** [comment]
This is my 5 top line on .csv file(exported by DOS /r/n) :
```
"00001","25938078","R","AM","GM","Y","1000",0,275,00000000,20170822,00000000,0,0.0000,0.0000,0.0000,0,0,0.00,0,0,0.00,0.00,0.00,0.0000,0,0.00,0.00,0.00,0.0000,0,0.00,0.00,0.00,0.0000,0,0.0000,0.0000,0.0000,0.0000,"IND","","","1","","NI","GM","0",133.50,0,1,"","CERTI FIT","CORVETTE1000",0.0000,00000000,00000000,"A","CORVETTE 05-12 RT.FT.FENDER*BASE MODEL","",""
"00002","25938077","R","AM","GM","Y","1000",0,275,00000000,00000000,00000000,0,0.0000,0.0000,0.0000,0,0,0.00,0,0,0.00,0.00,0.00,0.0000,0,0.00,0.00,0.00,0.0000,0,0.00,0.00,0.00,0.0000,0,0.0000,0.0000,0.0000,0.0000,"IND","","","1","","NI","GM","0",133.50,0,1,"","","CORVETTE1000",0.0000,00000000,00000000,"A","CORVETTE 05.LT.FT.FENDER*BASE MODEL","",""
"00005","30001898","R","AM","GM","Y","1000",0,3,20070821,20070820,20070820,0,0.0000,0000,0000,0,0,0.00,0,15,752.90,439.92,312.98,41.5699,0,0.00,0.00,0.00,0.0000,0,0.00,0.00,0.00,0.0000,0,0.0000,0.0000,0.0000,0.0000,"IND","","","1","","IN","GM","1",48.50,0,1,"GEM1001AR","NW","METRO1000",0.0000,00000000,00000000,"A","METRO/SWIFT 89-94 RT FENDER W/O =CONVERTABLE","",""
"00006","30001900","R","AM","GM","Y","1000",0,3,20060916,20060915,20060915,0,0.0000,0000,0000,0,0,0.00,0,13,754.60,327.33,427.27,56.6221,0,0.00,0.00,0.00,0.0000,0,0.00,0.00,0.00,0.0000,0,0.0000,0.0000,0.0000,0.0000,"IND","","","1","","IN","GM","1",48.50,0,1,"GEM1001AL","PARTCHANEL","METRO1000",0.0000,00000000,00000000,"A","METRO/SWIFT 89-94 LT*FENDER W/O CONVERTABLE","",""
"00009","94857068","R","AM","GM","Y","1000",1,4,20160518,20160518,20160518,0,0.0000,0000,0000,0,0,0.00,0,32,3294.50,1958.65,1335.85,40.5479,0,0.00,0.00,0.00,0.0000,2,264.00,181.50,82.50,31.2500,0,0.0000,0.0000,0.0000,0.0000,"IND","","","1","GM1241266","IN","GM","1",199.50,0,1,"","ADEP INT.","PRIZM1000",0.0000,00000000,00000000,"A","PRIZM 98-02 &RT FENDER","",""

```
[Enter steps to reproduce:]

1. open csv file
2. click on 'edit column name' in column head OR double click on cell to edit content

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: "Fedora release 27
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package 1.8.3


### Stack Trace

Uncaught TypeError: Cannot read property 'clearUndoStack' of undefined

```
At /home/vafa/.atom/packages/tablr/lib/table-element.js:1356

TypeError: Cannot read property 'clearUndoStack' of undefined
    at HTMLElement.startColumnEdit (/packages/tablr/lib/table-element.js:1356:38)
    at subscriptions.add.subscribeTo.click.e (/packages/tablr/lib/table-element.js:319:52)
    at /packages/tablr/lib/table-element.js:26:17
    at /packages/tablr/node_modules/atom-utils/lib/mixins/events-delegation.js:128:18
    at HTMLElement.module.exports.EventsDelegation.eachSelector (/packages/tablr/node_modules/atom-utils/lib/mixins/events-delegation.js:144:13)
    at /packages/tablr/node_modules/atom-utils/lib/mixins/events-delegation.js:122:22
    at HTMLElement.module.exports.EventsDelegation.nodeAndItsAncestors (/packages/tablr/node_modules/atom-utils/lib/mixins/events-delegation.js:169:7)
    at HTMLElement.module.exports.EventsDelegation.eachSelectorFromTarget (/packages/tablr/node_modules/atom-utils/lib/mixins/events-delegation.js:118:19)
    at HTMLDivElement.listener (/packages/tablr/node_modules/atom-utils/lib/mixins/events-delegation.js:105:15)
```

### Commands

```
     -8:31.3.0 core:move-left (input.hidden-input)
     -8:26.4.0 core:select-right (input.hidden-input)
  2x -8:24.9.0 core:backspace (input.hidden-input)
     -8:12.3.0 core:select-left (input.hidden-input)
 10x -4:43.4.0 core:move-left (input.hidden-input)
 66x -3:56.3.0 core:page-up (input.hidden-input)
undefined -3:41.4.0 core:select-page-down (input.hidden-input)
     -3:32.5.0 core:backspace (input.hidden-input)
     -3:27.8.0 core:save (input.hidden-input)
     -3:00.9.0 application:open-file (input.hidden-input)
```

### Non-Core Packages

```
atom-php-navigation 0.6.0 
data-ace 0.24.13 
laravel 0.7.1 
tablr 1.8.3 
```

**Comment by BenjaminHoegh** [comment]
Same issue on Windows 10 & MacOS

`TypeError: Cannot read property 'clearUndoStack' of undefined
    at HTMLElement.startCellEdit (/Users/HawkonDK/.atom/packages/tablr/lib/table-element.js:1309:36)
    at Object.dblclick (/Users/HawkonDK/.atom/packages/tablr/lib/table-element.js:341:29)
    at HTMLDivElement.listener (/Users/HawkonDK/.atom/packages/minimap/node_modules/atom-utils/lib/mixins/events-delegation.js:108:41)`

**Comment by eugenweissbart** [comment]
bump

**Comment by k-utsumi** [comment]
https://github.com/abe33/atom-tablr/issues/93#issuecomment-347242628

The file name was incorrect.
`table-elements.js` > `table-element.js`

Command to open file on terminal.
```
$ atom ~/.atom/packages/tablr/lib/table-element.js
```

---

I forked to https://github.com/k-utsumi/atom-tablr
